/*
This file is the panel in which your graphics are drawn. Do not modify it, except
for importing your class as packagename.classname at the end of the imports,
and setting externalClass to your class name as classname.class; doing otherwise
could yield unpredictable results, though most predictably would keep the program
from working.

This class uses reflection to access a method called "paint" in your graphics
class. This method must have exactly one parameter, a java.awt.Graphics
object which receives the graphics context from this JPanel.
*/
package graphicsbase;

import java.awt.Graphics;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import randomDice.randomDice;

/**
 *
 * @author scott.walker@ectorcountyisd.org
 */
public class GraphicsPanel extends javax.swing.JPanel {

    //Your class name also goes here, as classname.class
    Class externalClass = randomDice.class;
    
    /**
     * Creates new form GraphicsPanel
     */
    public GraphicsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        Method[] externalMethods = externalClass.getMethods();
        Method externalPaint = Arrays.stream(externalMethods)
                .filter(m -> "paint".equals(m.getName())).findFirst().get();
               
        Object target = null;
        try {
            target = externalClass.getDeclaredConstructor((Class[]) null).newInstance((Object[]) null);
        } catch (NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(GraphicsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            externalPaint.invoke(target, g);
        } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(GraphicsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
